import { Fragment, useMemo, useState } from "react";
import { ChevronDown, ChevronRight, MousePointerClick } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatarMoeda, formatarNumero, formatarPercentual } from "@/lib/formatters";
import type { ItemDepartamentoAnalise } from "@/lib/vendas";
import { DataBarPercent } from "./data-bar-percent";
import { MetricaCard } from "@/components/metrica-card";
import { ReportViewToggle } from "./report-view-toggle";

export function AbaDepartamentos({ deptosFiltrados }: { deptosFiltrados: ItemDepartamentoAnalise[] }) {
  const [visao, setVisao] = useState<"sintetico" | "analitico">("sintetico");
  const [aberto, setAberto] = useState<string | null>(null);
  const total = useMemo(() => deptosFiltrados.reduce((soma, dep) => soma + dep.faturamento, 0), [deptosFiltrados]);
  const itens = useMemo(() => deptosFiltrados.flatMap((dep) => dep.produtos.map((produto) => ({ ...produto, departamento: dep.nome }))), [deptosFiltrados]);
  const alternar = (nome: string) => setAberto((atual) => atual === nome ? null : nome);
  return <div className="space-y-4">
    <ReportViewToggle visao={visao} onChange={setVisao} rotuloAnalitico="Produtos detalhados" descricao="Síntese compara departamentos; produtos detalhados mostram os itens que formam cada resultado." />
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><MetricaCard rotulo="Departamentos" definicao="Quantidade de departamentos com venda no período." valor={formatarNumero(deptosFiltrados.length, 0)} /><MetricaCard rotulo="Produtos vendidos" definicao="Produtos distintos vendidos nos departamentos filtrados." valor={formatarNumero(itens.length, 0)} destaque="primario" /><MetricaCard rotulo="Faturamento total" definicao="Soma do faturamento dos departamentos filtrados." valor={formatarMoeda(total)} destaque="primario" /></div>
    {visao === "analitico" ? <div className="overflow-x-auto rounded-md border"><table className="w-full min-w-[760px] text-xs"><thead><tr className="border-b bg-muted/40 text-left font-bold text-muted-foreground"><th className="p-3">Departamento</th><th className="p-3">Código</th><th className="p-3">Produto</th><th className="p-3 text-right">Quantidade</th><th className="p-3 text-right">Preço médio</th><th className="p-3 text-right">Faturamento</th></tr></thead><tbody>{itens.map((item) => <tr key={`${item.departamento}-${item.id}`} className="border-b last:border-0 hover:bg-muted/20"><td className="p-3 font-semibold">{item.departamento}</td><td className="p-3 font-mono">{item.id}</td><td className="p-3">{item.produto}</td><td className="p-3 text-right font-mono">{formatarNumero(item.quantidade, 2)} {item.un}</td><td className="p-3 text-right font-mono">{formatarMoeda(item.precoMedio)}</td><td className="p-3 text-right font-mono font-bold">{formatarMoeda(item.total)}</td></tr>)}</tbody></table></div> : <div className="overflow-x-auto rounded-md border"><table className="w-full min-w-[700px] text-xs"><thead><tr className="border-b bg-muted/40 text-left font-bold text-muted-foreground"><th className="w-10 p-3" /><th className="p-3">Departamento</th><th className="p-3 text-right">Produtos</th><th className="p-3 text-right">Itens</th><th className="p-3 text-right">Preço médio</th><th className="p-3 text-right">Faturamento</th><th className="p-3 text-right">Participação</th></tr></thead><tbody>{deptosFiltrados.map((dep) => { const isOpen = aberto === dep.nome; return <Fragment key={dep.nome}><tr className={`border-b hover:bg-muted/20 ${isOpen ? "bg-muted/30" : ""}`}><td className="p-3"><Button size="icon-sm" variant="ghost" onClick={() => alternar(dep.nome)} aria-label={`${isOpen ? "Fechar" : "Abrir"} itens de ${dep.nome}`}>{isOpen ? <ChevronDown /> : <ChevronRight />}</Button></td><td className="p-3 font-bold"><button type="button" onClick={() => alternar(dep.nome)} className="inline-flex items-center gap-1.5 hover:text-primary hover:underline" aria-expanded={isOpen}>{dep.nome}<MousePointerClick className="size-3 text-muted-foreground/60" /></button></td><td className="p-3 text-right font-mono">{dep.quantidadeProdutosDistintos}</td><td className="p-3 text-right font-mono">{formatarNumero(dep.quantidadeItens, 2)}</td><td className="p-3 text-right font-mono">{formatarMoeda(dep.ticketMedioPorItem)}</td><td className="p-3 text-right font-mono font-bold">{formatarMoeda(dep.faturamento)}</td><td className="p-3 text-right"><DataBarPercent valor={formatarPercentual(dep.percentual, 1)} percentual={dep.percentual} cor="bg-blue-500/20" /></td></tr>{isOpen ? <tr><td colSpan={7} className="bg-muted/20 p-4 text-xs text-muted-foreground">{dep.produtos.length} produtos no departamento. Use “Produtos detalhados” para comparar todos.</td></tr> : null}</Fragment>; })}</tbody></table></div>}
  </div>;
}
